#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#define NULL ((void *)0)
#define XLWIP_CONFIG_N_TX_DESC 64
#define XLWIP_CONFIG_N_RX_DESC 64
#define NETIF_MAX_HWADDR_LEN 6U
#define MEM_ALIGNMENT 64
#define PBUF_POOL_BUFSIZE 1700


#endif /* CONSTANTS_H_ */
